Beta test 2
RobinAmsters/ROS_workshop pull request #45
Opened 2018-03-28 21:51 UTC by RobinAmsters

Small edits after second beta test

2018-03-28 21:54 UTC, RobinAmsters commented
I'm relatively sure we can take the version already on master for the third tutorial. Not sure what went wrong there

2018-03-29 12:50 UTC, ratking82 approved these changes
Approved but not read! :disappointed:

2018-03-29 12:52 UTC, ratking82 requested changes
There is a merge conflict. Please fix and submit a PR.

2018-03-29 16:02 UTC, ratking82 approved these changes

2018-03-29 16:03 UTC, merged